/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import Model.Validations.UserDataValidations;
import ficheros.ClassFichero;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
//esto es para centrar el formulario
import java.awt.Dimension;
import java.awt.Toolkit;
//importar archivos
import java.io.*;
import java.text.SimpleDateFormat;
//calendario
import java.util.Date;
import exceptions.ErrDNIFormatException;
import exceptions.ErrPostalCodeException;

/**
 *
 * @author mariaandoli
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        initConfig();
        setSize(800, 600);
        setLocationCenter();
    }

    private void initConfig() {
        //aqui se pone como extra se tiene que investigar un poco
        boolean Habilitar = true;
        boolean noHabilitar = false;
//        if (jButtonClear.equals(Habilitar) && jButtonValidate.equals(Habilitar)) {
//            jButtonClear.setEnabled(Habilitar);
//            jButtonValidate.setEnabled(Habilitar);
//        }
        if (Habilitar == true) {
            jButtonClear.setEnabled(true);
            jButtonValidate.setEnabled(true);
        }
        //if (!jButtonCSV.equals(Habilitar)) {
        jButtonCSV.setEnabled(noHabilitar);

        //que los textfields esten vacios igual que los labels
        jTextFieldRespuestCP.setEditable(Habilitar);
        jTextFieldRespuestaEmail.setEditable(Habilitar);
        jTextFieldRespuestaNIF.setEditable(Habilitar);
        jTextFieldRespuesta.setEditable(Habilitar);
        jTextFieldRespuestDataBirth.setEditable(Habilitar);

    }

    private void btnObtenerFechaActionPerformed(java.awt.event.ActionEvent evt) {

        //     Date fecha = jTextFieldRespuestDataBirth.getText();
//        
//        //Formato de Fecha
//   
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
//        
        //    77 txtSalida.setText("La fecha es: " + formato.format(fecha));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldName = new javax.swing.JPanel();
        jlabeltitulo = new javax.swing.JLabel();
        jLabelLogoImg = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldRespuesta = new javax.swing.JTextField();
        jLabelErrName = new javax.swing.JLabel();
        jLabelNIF = new javax.swing.JLabel();
        jTextFieldRespuestaNIF = new javax.swing.JTextField();
        jLabelErrName1 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldRespuestaEmail = new javax.swing.JTextField();
        jLabelErrEmail = new javax.swing.JLabel();
        jLabelDataBirth = new javax.swing.JLabel();
        jTextFieldRespuestDataBirth = new javax.swing.JTextField();
        jLabelErrDataBirth = new javax.swing.JLabel();
        jLabelCP = new javax.swing.JLabel();
        jTextFieldRespuestCP = new javax.swing.JTextField();
        jLabelErrCP = new javax.swing.JLabel();
        jLabelBirthCalc = new javax.swing.JLabel();
        jTextFieldRespuestaEddadCalc = new javax.swing.JTextField();
        jLabelErrEdadCalc = new javax.swing.JLabel();
        jButtonValidate = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonCSV = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabeltitulo.setBackground(new java.awt.Color(204, 255, 204));
        jlabeltitulo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jlabeltitulo.setForeground(new java.awt.Color(0, 153, 0));
        jlabeltitulo.setText("Validator Data User");
        jlabeltitulo.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        jlabeltitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jlabeltitulo.setFocusCycleRoot(true);

        jLabelLogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/gui/media/logo.png"))); // NOI18N

        jLabelName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabelName.setText("Name");

        jLabelErrName.setForeground(new java.awt.Color(255, 0, 0));

        jLabelNIF.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabelNIF.setText("NIF");

        jLabelErrName1.setForeground(new java.awt.Color(255, 0, 0));

        jLabelEmail.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelErrEmail.setForeground(new java.awt.Color(255, 0, 0));

        jLabelDataBirth.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabelDataBirth.setText("Fecha de nacimiento");

        jTextFieldRespuestDataBirth.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldRespuestDataBirth.setText("dd/MM/yyyy");
        jTextFieldRespuestDataBirth.setCaretColor(new java.awt.Color(153, 153, 153));
        jTextFieldRespuestDataBirth.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        jTextFieldRespuestDataBirth.setSelectionColor(new java.awt.Color(153, 153, 153));

        jLabelErrDataBirth.setForeground(new java.awt.Color(255, 0, 0));

        jLabelCP.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabelCP.setText("Codigo Postal");

        jLabelErrCP.setForeground(new java.awt.Color(255, 0, 0));

        jLabelBirthCalc.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabelBirthCalc.setText("Edad calculada");

        jLabelErrEdadCalc.setForeground(new java.awt.Color(255, 0, 0));

        jButtonValidate.setText("Validate");
        jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidateActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonCSV.setText("CSV");
        jButtonCSV.setToolTipText("");
        jButtonCSV.setEnabled(false);
        jButtonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTextFieldNameLayout = new javax.swing.GroupLayout(jTextFieldName);
        jTextFieldName.setLayout(jTextFieldNameLayout);
        jTextFieldNameLayout.setHorizontalGroup(
            jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFieldNameLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlabeltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogoImg)
                .addGap(440, 440, 440))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFieldNameLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTextFieldNameLayout.createSequentialGroup()
                        .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jTextFieldNameLayout.createSequentialGroup()
                                .addComponent(jLabelErrName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(161, 161, 161))
                            .addComponent(jLabelName)
                            .addComponent(jTextFieldRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelErrEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jTextFieldRespuestaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelErrName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNIF)
                                    .addComponent(jTextFieldRespuestaNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelErrEdadCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelBirthCalc)
                                .addComponent(jTextFieldRespuestaEddadCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelErrDataBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDataBirth)
                                    .addComponent(jTextFieldRespuestDataBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelCP)
                                    .addComponent(jTextFieldRespuestCP, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(jLabelErrCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jTextFieldNameLayout.createSequentialGroup()
                        .addComponent(jButtonCSV)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonValidate)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(82, 82, 82)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(407, 407, 407))
        );
        jTextFieldNameLayout.setVerticalGroup(
            jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTextFieldNameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogoImg))
                .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFieldNameLayout.createSequentialGroup()
                        .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jTextFieldNameLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jTextFieldNameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jTextFieldNameLayout.createSequentialGroup()
                                        .addComponent(jLabelDataBirth)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldRespuestDataBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelErrDataBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelBirthCalc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldRespuestaEddadCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelErrEdadCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jTextFieldNameLayout.createSequentialGroup()
                                        .addComponent(jLabelName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelErrName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelNIF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldRespuestaNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelErrName1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRespuestaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFieldNameLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelCP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRespuestCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErrCP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jTextFieldNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCSV)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonValidate))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformed
        // TODO add your handling code here:
        boolean allOk = true;
        String name = jTextFieldRespuesta.getText();
        if (!UserDataValidations.checkName(name)) //si no pone un nombre normal que te salga el error
        {
            jLabelErrName.setText("Nombre incorrecto....");
            allOk = false;
        }

        String NIF = jTextFieldRespuestaNIF.getText();
        try {
            if (!NIF.matches("\\d+")) {
                jLabelErrName1.setText("NIF debe ser un número.");
                allOk = false;
            } else {
                UserDataValidations.checkId(1, NIF);
            }
        } catch (ErrDNIFormatException ex) {
            allOk = false;
            jLabelErrName1.setText(ex.getMessage() );

        }
        String email = jTextFieldRespuestaEmail.getText();
        if (!UserDataValidations.checkEmail(email)) {
            jLabelErrEmail.setText("Email incorrecto....");
            allOk = false;

        }
        String date = jTextFieldRespuestDataBirth.getText();
        if (!UserDataValidations.checkFormatDate(date)) {
            jLabelErrDataBirth.setText("Fecha incorrecta....");
            allOk = false;
        }
        String CP = jTextFieldRespuestCP.getText();

        try {
            if (!CP.matches("\\d{5}")) {
                throw new ErrPostalCodeException("El código postal debe tener 5 dígitos numéricos.");
            }
            UserDataValidations.checkPostalCode(CP);
        } catch (ErrPostalCodeException ex) {
            allOk = false;
            jLabelErrCP.setText("Código Postal incorrecto: \n" + ex.getMessage());
        }
        if (allOk == true) {
            jTextFieldRespuestCP.setEditable(false);
            jTextFieldRespuestaEmail.setEditable(false);
            jTextFieldRespuestaNIF.setEditable(false);
            jTextFieldRespuesta.setEditable(false);
            jTextFieldRespuestDataBirth.setEditable(false);
            jButtonValidate.setEnabled(false);
            jButtonCSV.setEnabled(true);
        }

        //si el texto tiene la fecha que me calcule la edad 
        String fecha = jTextFieldRespuestDataBirth.getText();
        if (UserDataValidations.checkFormatDate(date)) {
            int age = UserDataValidations.calculateAge(date);
            jTextFieldRespuestaEddadCalc.setText(String.valueOf(age));
        } else {
            jLabelErrDataBirth.setText("Fecha incorrecta...");
        }

    }//GEN-LAST:event_jButtonValidateActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        //reinicio de los botones menos CSV
        jTextFieldRespuestCP.setText("");
        jTextFieldRespuestaEmail.setText("");
        jTextFieldRespuestaNIF.setText(" ");
        jTextFieldRespuesta.setText(" ");
        jTextFieldRespuestDataBirth.setText("");
        jTextFieldRespuestaEddadCalc.setText(" ");

        //mensajes de error
        jLabelErrCP.setText("");
        jLabelErrDataBirth.setText("");
        jLabelErrEmail.setText("");
        jLabelErrName.setText("");
        jLabelErrName1.setText(" ");

        //q se vuelvan para escribir
        jTextFieldRespuestCP.setEditable(true);
        jTextFieldRespuestaEmail.setEditable(true);
        jTextFieldRespuestaNIF.setEditable(true);
        jTextFieldRespuesta.setEditable(true);
        jTextFieldRespuestDataBirth.setEditable(true);
        jButtonValidate.setEnabled(true);
        jButtonCSV.setEnabled(false);


    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed
        // TODO add your handling code here:
        jButtonCSV.isEnabled();
        String name = jTextFieldRespuesta.getText();
        String NIF = jTextFieldRespuestaNIF.getText();
        String email = jTextFieldRespuestaEmail.getText();
        String date = jTextFieldRespuestDataBirth.getText();
        String CP = jTextFieldRespuestCP.getText();

        //que me lo pase como a t5exto literal para asi ponerlol en el regustro lalala
        String archivocsv = "user_data_MAO.csv";
        File archivo = new File(archivocsv);
        String line = name + ";" + NIF + ";" + email + ";" + date + ";" + CP + "\n";
        ClassFichero.writeFile(line);

        //que cuando se gfuatden los datos se cierre el boton    
        jButtonCSV.setEnabled(false);
    }//GEN-LAST:event_jButtonCSVActionPerformed

    public void setLocationCenter() {
        setLocationMove(0, 0);
    }

    public void setLocationMove(int moveWidth, int moveHeight) {
        // Obtenemos el tamaño de la pantalla.
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        // Obtenemos el tamaño de nuestro frame.
        Dimension frameSize = this.getSize();
        frameSize.width = frameSize.width > screenSize.width ? screenSize.width : frameSize.width;
        frameSize.height = frameSize.height > screenSize.height ? screenSize.height : frameSize.height;
        // We define the location. Definimos la localización.
        setLocation((screenSize.width - frameSize.width) / 2 + moveWidth,
                (screenSize.height - frameSize.height) / 2 + moveHeight);
    }

    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        ClassFichero.createFile("user_data_MAO.csv");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonValidate;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabelBirthCalc;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelDataBirth;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelErrCP;
    private javax.swing.JLabel jLabelErrDataBirth;
    private javax.swing.JLabel jLabelErrEdadCalc;
    private javax.swing.JLabel jLabelErrEmail;
    private javax.swing.JLabel jLabelErrName;
    private javax.swing.JLabel jLabelErrName1;
    private javax.swing.JLabel jLabelLogoImg;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jTextFieldName;
    private javax.swing.JTextField jTextFieldRespuestCP;
    private javax.swing.JTextField jTextFieldRespuestDataBirth;
    private javax.swing.JTextField jTextFieldRespuesta;
    private javax.swing.JTextField jTextFieldRespuestaEddadCalc;
    private javax.swing.JTextField jTextFieldRespuestaEmail;
    private javax.swing.JTextField jTextFieldRespuestaNIF;
    private javax.swing.JLabel jlabeltitulo;
    // End of variables declaration//GEN-END:variables
}
